//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstruMarket_ERP_V0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSCAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ODSCAB()
        {
            this.ODSETs = new HashSet<ODSET>();
        }
    
        public int idodscab { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> idmecanico { get; set; }
        public Nullable<int> idequipo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual MECANICO MECANICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODSET> ODSETs { get; set; }
    }
}
