//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstruMarket_ERP_V0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSET
    {
        public int idodsset { get; set; }
        public Nullable<int> idodscab { get; set; }
        public Nullable<int> idproducto { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual ODSCAB ODSCAB { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
