//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstruMarket_ERP_V0._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TALLEREntities1 : DbContext
    {
        public TALLEREntities1()
            : base("name=TALLEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAEQUIPO> CATEGORIAEQUIPOes { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<EQUIPO> EQUIPOes { get; set; }
        public virtual DbSet<MECANICO> MECANICOes { get; set; }
        public virtual DbSet<ODSCAB> ODSCABs { get; set; }
        public virtual DbSet<ODSET> ODSETs { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
    }
}
